using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Quitchet.Core.Models.Agent
{
    public class AgentlistPopUPFullDetails
    {
        public string CheckInStatus { get; set; }
        public string Running_Time_Duration { get; set; }
        public string MLSNO { get; set; }
        public string SHOWING { get; set; }
        public string ListPrice { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string GeoSubdiv { get; set; }
        public string GeoPostCd { get; set; }
        public string Agent { get; set; }
        public string Class { get; set; }
        public string Status { get; set; }
        public string WhoToContact { get; set; }
        public string Instructions { get; set; }
        public string Type { get; set; }
        public string YearBuilt { get; set; }
        public string LotSize { get; set; }
        public string Subdiv { get; set; }
        public string NoStor { get; set; }
        public string Bedrooms { get; set; }
        public string Bathrooms { get; set; }
        public string SqFt { get; set; }
        public string GarType { get; set; }
        public string GarCap { get; set; }
        public string LivRmSz { get; set; }
        public string DinRmSz { get; set; }
        public string BrkftSz { get; set; }
        public string BOrRSz { get; set; }
        public string SunRSz { get; set; }
        public string MstrBdSz { get; set; }
        public string Bed2Sz { get; set; }
        public string Bed3Sz { get; set; }
        public string Bed4Sz { get; set; }
        public string Bed5Sz { get; set; }
        public string DeckSz { get; set; }
        public string PatioSz { get; set; }
        public string LnSz { get; set; }
        public string Elementary { get; set; }
        public string Middle { get; set; }
        public string High { get; set; }
        public string APPLIANCES { get; set; }
        public string FLOORS { get; set; }
        public string MRBEDFETRS { get; set; }
        public string LAUNDRY { get; set; }
        public string SPECILTYRM { get; set; }
        public string FIREPLACE { get; set; }
        public string BASEMENT { get; set; }
        public string STORAGESPC { get; set; }
        public string INTERRFTRS { get; set; }
        public string LOTDSCRPTN { get; set; }
        public string FOUNDATION { get; set; }
        public string EXTERRFNSH { get; set; }
        public string ROOF { get; set; }
        public string DRIVEWAY { get; set; }
        public string EXTERRFTRS { get; set; }
        public string HOA { get; set; }
        public string Condo { get; set; }
        public string WATER { get; set; }
        public string SEWER { get; set; }
        public string GARBAGPCKP { get; set; }
        public string WATERHEATR { get; set; }
        public string HETNGSYSTM { get; set; }
        public string COLNGSYSTM { get; set; }
        public string HOACntct { get; set; }
        public string ADITIONLFS { get; set; }
        public string SPECLFNNCS { get; set; }
        public string TotalTax { get; set; }
        public string TaxYear { get; set; }
        public string PhotoCount { get; set; }
        public string PhotoLocation { get; set; }
        public string GeoLat { get; set; }
        public string GeoLong { get; set; }
        public string ListingAgent_FirstName { get; set; }
        public string ListingAgent_LastName { get; set; }
        public string ListingAgent_Email { get; set; }
        public string Phone1Nbr { get; set; }
        public string Phone2Nbr { get; set; }
        public string ListingAgent_Office { get; set; }
        public string ListingAgent_BoardID { get; set; }
        public string ListingAgent_Image { get; set; }
        public string DOCSONFILE { get; set; }
        public string MemberRmk { get; set; }
        public string CustRmk { get; set; }
        public string HOATerm { get; set; }
        public string HAOrRegime { get; set; }
        public string DaysInQuitchet { get; set; }
        public string DCMNTSWTHF { get; set; }
        public string ConsRmks { get; set; }
        public string Is_Viewd { get; set; }
        public string Is_Favorite { get; set; }
        public string LAKPRPFTRS { get; set; }
        public string EQSTRNPRPF { get; set; }
        public string ROADFRONTG { get; set; }
        public string TOPOGRAPHY { get; set; }
        public string AMENTSNCLD { get; set; }
        public string PRPDSCRPTN { get; set; }
        public string COVENANTS { get; set; }
        public string RESTRICTNS { get; set; }
        public String HCMNTYMNTS { get; set; }
        public string CNDRGMNCLD { get; set; }
        public string PK_RequestShowingID { get; set; }
        public string PK_ShowingSafetySettingsID { get; set; }
        public string SH_SafetyTimerStatue { get; set; }
        public string SH_EmergencyContact { get; set; }
        public string SH_EmergencyContactName { get; set; }
        public string SH_SafetyTimerLimit { get; set; }
        public string SH_TimerExtensionAgent { get; set; }
        public string SH_TimerAuthCode { get; set; }
        public string SH_EmergencyCode { get; set; }
        public string SH_Call_TimerExpire { get; set; }
        public string SH_TextEmergContact_TimerExpire { get; set; }
        public string SH_Message_TimerExpire { get; set; }
        public string SH_Call_CodeEntered { get; set; }
        public string SH_TextEmergContact_CodeEntered { get; set; }
        public string SH_Message_CodeEntered { get; set; }
        public string Running_Time { get; set; }
        public string Sale_Rent { get; set; }
        ////////////////////////////////
        public string DCMNTSWTHF_NEW { get; set; }
        public string DOCSONFILE_NEW { get; set; }
        public string SHOWING_NEW { get; set; }
        public string HCMNTYMNTS_NEW { get; set; }
        public string GarType_NEW { get; set; }
        public string APPLIANCES_NEW { get; set; }
        public string FLOORS_NEW { get; set; }
        public string LAUNDRY_NEW { get; set; }
        public string FIREPLACE_NEW { get; set; }
        public string INTERRFTRS_NEW { get; set; }
        public string EXTERRFNSH_NEW { get; set; }
        public string ROOF_NEW { get; set; }
        public string DRIVEWAY_NEW { get; set; }
        public string EXTERRFTRS_NEW { get; set; }
        public string HETNGSYSTM_NEW { get; set; }
        public string ListingAgent_PkUserID { get; set; }
        public string Primary_Color { get; set; }
        public string Secondary_Color { get; set; }
        public string Age { get; set; }
        public string SoldPrice { get; set; }
    }
}
